[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.localnet]
cursed_valaks_vault = "HZRbgxuHRSLFRn8JbbjBeKt6yxHsTHQQ83DarAY1puqu"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = '~\.config\solana\id.json'

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
